-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 19:10:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema public_information
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public_information
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public_information` DEFAULT CHARACTER SET utf8 ;
USE `public_information` ;

-- -----------------------------------------------------
-- Table `public_information`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`location` (
  `idlocation` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `latitude` POINT NULL,
  `longitude` POINT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`user` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(1) NOT NULL,
  `birth_date` DATE NULL,
  `last_acess` DATE NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_usuario_localizacao1_idx` (`location_idlocation` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_localizacao1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `public_information`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`access_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`access_point` (
  `idaccess_point` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `internet_access` VARCHAR(1) NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`idaccess_point`),
  INDEX `fk_pontos_acesso_localizacao_idx` (`location_idlocation` ASC) VISIBLE,
  CONSTRAINT `fk_pontos_acesso_localizacao`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `public_information`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`post` (
  `idpost` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `category` VARCHAR(45) NULL,
  `date` DATE NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_postagem_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`suggestion` (
  `idsuggestion` INT NOT NULL,
  `description` VARCHAR(300) NULL,
  `date` DATE NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idsuggestion`),
  INDEX `fk_sugestoes_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_sugestoes_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`comment` (
  `idcomment` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `like` INT NULL,
  `date` DATE NULL,
  `tag` VARCHAR(45) NULL,
  `post_idpost` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comentarios_postagem1_idx` (`post_idpost` ASC) VISIBLE,
  INDEX `fk_comentarios_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_postagem1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `public_information`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
