-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 15:48:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema public_info
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public_info
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public_info` DEFAULT CHARACTER SET utf8 ;
USE `public_info` ;

-- -----------------------------------------------------
-- Table `public_info`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `latitude` POINT NULL,
  `longitude` POINT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(1) NOT NULL,
  `birth_date` DATE NOT NULL,
  `last_acess` DATETIME NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`suggestion` (
  ` idsuggestion` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `user_idUser` INT NOT NULL,
  `location_idlocation` INT NULL,
  PRIMARY KEY (` idsuggestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `category_idcategory` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `like` INT NULL,
  `date` DATETIME NOT NULL,
  `tag` VARCHAR(45) NULL,
  `user_idUser` INT NOT NULL,
  `post_idpost` INT NOT NULL,
  PRIMARY KEY (`idcomment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`types` (
  `idtypes` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_info`.`access_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_info`.`access_point` (
  `idaccess_point` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `internet_access` VARCHAR(1) NULL,
  `types_idtypes` INT NOT NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`idaccess_point`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
