-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 10:17:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema public_information
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public_information
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public_information` DEFAULT CHARACTER SET utf8 ;
USE `public_information` ;

-- -----------------------------------------------------
-- Table `public_information`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `distric` VARCHAR(45) NOT NULL,
  `latitude` POINT NULL,
  `longitude` POINT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(1) NOT NULL,
  `birth_date` DATE NOT NULL,
  `last_acess` DATETIME NULL,
  `location_idlocation` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_usuario_localizacao1_idx` (`location_idlocation` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_localizacao1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `public_information`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`types` (
  `idtypes` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`access_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`access_point` (
  `idaccess_point` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `internet_access` VARCHAR(1) NULL,
  `location_idlocation` INT NOT NULL,
  `types_idtypes` INT NOT NULL,
  PRIMARY KEY (`idaccess_point`),
  INDEX `fk_pontos_acesso_localizacao_idx` (`location_idlocation` ASC) VISIBLE,
  INDEX `fk_access_point_types1_idx` (`types_idtypes` ASC) VISIBLE,
  CONSTRAINT `fk_pontos_acesso_localizacao`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `public_information`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_point_types1`
    FOREIGN KEY (`types_idtypes`)
    REFERENCES `public_information`.`types` (`idtypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `user_idUser` INT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_postagem_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_post_category1_idx` (`category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `public_information`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`suggestion` (
  `idsuggestion` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `date` DATETIME NOT NULL,
  `user_idUser` INT NOT NULL,
  `location_idlocation` INT NULL,
  PRIMARY KEY (`idsuggestion`),
  INDEX `fk_sugestoes_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_suggestion_location1_idx` (`location_idlocation` ASC) VISIBLE,
  CONSTRAINT `fk_sugestoes_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suggestion_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `public_information`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public_information`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_information`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NOT NULL,
  `like` INT NULL,
  `date` DATETIME NOT NULL,
  `tag` VARCHAR(45) NULL,
  `post_idpost` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comentarios_postagem1_idx` (`post_idpost` ASC) VISIBLE,
  INDEX `fk_comentarios_usuario1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_postagem1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `public_information`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `public_information`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
